name: PHP Code Quality Diagnostics

on: [pull_request]

env:
  PHPCQ_DIRECTORY: ./phpcq-runner

jobs:
  build:
    runs-on: ubuntu-latest

    name: PHP ${{ matrix.php }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - php: 7.3
            output: '-o default'
          - php: 7.4
            output: '-o github-action -o default'

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug2

      - name: Install dependencies
        run: composer update --prefer-stable --no-interaction --no-progress --prefer-dist
        env:
          COMPOSER_ROOT_VERSION: dev-master

      - name: Update phpcq
        run: $GITHUB_WORKSPACE/vendor/bin/phpcq self-update

      - name: Install phpcq toolchain
        run: $GITHUB_WORKSPACE/vendor/bin/phpcq update -v --trust-keys

      - name: Run tests
        run: $GITHUB_WORKSPACE/vendor/bin/phpcq run -v ${{ matrix.output }}
